export default {
  Inter_500Medium: require('../assets/fonts/Inter_500Medium.ttf'),
  Inter_500Medium: require('../assets/fonts/Inter_500Medium.ttf'),
  Inter_300Light: require('../assets/fonts/Inter_300Light.ttf'),
  Inter_500Medium: require('../assets/fonts/Inter_500Medium.ttf'),
  Inter_600SemiBold: require('../assets/fonts/Inter_600SemiBold.ttf'),
  Inter_500Medium: require('../assets/fonts/Inter_500Medium.ttf'),
  Inter_300Light: require('../assets/fonts/Inter_300Light.ttf'),
  Inter_400Regular: require('../assets/fonts/Inter_400Regular.ttf'),
  RedHatDisplay_700Bold: require('../assets/fonts/RedHatDisplay_700Bold.ttf'),
  RedHatDisplay_500Medium: require('../assets/fonts/RedHatDisplay_500Medium.ttf'),
  RedHatDisplay_900Black: require('../assets/fonts/RedHatDisplay_900Black.ttf'),
  RedHatDisplay_500Medium: require('../assets/fonts/RedHatDisplay_500Medium.ttf'),
  RedHatDisplay_500Medium: require('../assets/fonts/RedHatDisplay_500Medium.ttf'),
  RedHatDisplay_700Bold: require('../assets/fonts/RedHatDisplay_700Bold.ttf'),
  RedHatDisplay_600SemiBold: require('../assets/fonts/RedHatDisplay_600SemiBold.ttf'),
};
