export default {
  SignUpScreenStill: require('../assets/images/SignUpScreen(Still).png'),
  Image30: require('../assets/images/Image30.png'),
  Logopixellate1: require('../assets/images/Logopixellate1.png'),
  Blatter1: require('../assets/images/Blatter1.png'),
  Uniclo: require('../assets/images/Uniclo.png'),
  Ellipse2: require('../assets/images/Ellipse2.png'),
  FitButtonMainScreen1: require('../assets/images/FitButton(MainScreen(1).png'),
  BackButton: require('../assets/images/BackButton.png'),
  Image1: require('../assets/images/Image1.png'),
  SearchCircle: require('../assets/images/Search(Circle).png'),
  Ellipse5: require('../assets/images/Ellipse5.png'),
  Home01: require('../assets/images/Home01.png'),
  Camera01: require('../assets/images/Camera01.png'),
  Compass03: require('../assets/images/Compass03.png'),
  Icon: require('../assets/images/Icon.png'),
  OutfitSelect3Button: require('../assets/images/OutfitSelect3Button.png'),
  SquareBrandButton: require('../assets/images/SquareBrandButton.png'),
  Rectangle15: require('../assets/images/Rectangle15.png'),
};
